services:
  nginx:
    image: tgv/nginx
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "127.0.0.1:8100:80"
    env_file:
      - .env
    networks:
      - alpha

  python-fetcher:
    image: tgv/fetcher
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile.python-fetcher
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    env_file:
      - .env
    command: ["/bin/sh", "-c", "while true; do python fetcher.py sources/items_all.yaml --wait-for-healthy --batch-size 128; echo 'Sleeping...'; sleep 86400; done"]
    volumes:
      - "./data/:/app/data:rw"
    networks:
      - alpha

  typesense:
    image: tgv/typesense
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile.typesense
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    volumes:
      - "./typesense-data/:/data:rw"
    ports:
      - "127.0.0.1:8108:8108"
    networks:
      - alpha

networks:
  alpha:
