services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "127.0.0.1:80:80"
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_UPSTREAM_HOST=${TYPESENSE_UPSTREAM_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL}
      - TYPESENSE_PATH=${TYPESENSE_PATH}
    networks:
      - alpha
      
  python-fetcher:
    build:
      context: .
      dockerfile: docker/Dockerfile.python-fetcher
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    networks:
      - alpha

  typesense:
    build:
      context: .
      dockerfile: docker/Dockerfile.typesense
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    networks:
      - alpha

networks:
  alpha:
    driver: bridge